// <auto-generated />
using System;
using FlightBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightBooking.Migrations
{
    [DbContext(typeof(FlightBookingContext))]
    partial class FlightBookingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightBooking.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("FlightBooking.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArrivalCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Airline = "American Airlines",
                            ArrivalCity = "Los Angeles",
                            ArrivalTime = new DateTime(2026, 6, 15, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 150,
                            DepartureCity = "New York",
                            DepartureTime = new DateTime(2026, 6, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "AA101",
                            Price = 349.99m
                        },
                        new
                        {
                            Id = 2,
                            Airline = "United Airlines",
                            ArrivalCity = "Miami",
                            ArrivalTime = new DateTime(2026, 6, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 120,
                            DepartureCity = "Chicago",
                            DepartureTime = new DateTime(2026, 6, 16, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "UA202",
                            Price = 279.99m
                        },
                        new
                        {
                            Id = 3,
                            Airline = "Delta Airlines",
                            ArrivalCity = "Seattle",
                            ArrivalTime = new DateTime(2026, 6, 17, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 80,
                            DepartureCity = "San Francisco",
                            DepartureTime = new DateTime(2026, 6, 17, 6, 30, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "DL303",
                            Price = 189.99m
                        },
                        new
                        {
                            Id = 4,
                            Airline = "Southwest Airlines",
                            ArrivalCity = "Denver",
                            ArrivalTime = new DateTime(2026, 6, 18, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 175,
                            DepartureCity = "Dallas",
                            DepartureTime = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "SW404",
                            Price = 159.99m
                        },
                        new
                        {
                            Id = 5,
                            Airline = "JetBlue",
                            ArrivalCity = "Orlando",
                            ArrivalTime = new DateTime(2026, 6, 19, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 100,
                            DepartureCity = "Boston",
                            DepartureTime = new DateTime(2026, 6, 19, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "JB505",
                            Price = 229.99m
                        });
                });

            modelBuilder.Entity("FlightBooking.Models.Booking", b =>
                {
                    b.HasOne("FlightBooking.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });
#pragma warning restore 612, 618
        }
    }
}
